spring.application.name=prescripto

# Database
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Redis ? use URL only, remove hardcoded host/port
spring.redis.url=${SPRING_REDIS_URL}
spring.redis.ssl.enabled=false
spring.redis.timeout=60000

# Server
server.port=${SERVER_PORT:8090}

# Admin
adminEmail=${ADMIN_EMAIL}
adminPassword=${ADMIN_PASSWORD}

# Stripe
stripe.secret.Key=${STRIPE_SECRET_KEY}
stripe.CURRENCY=inr

spring.main.allow-bean-definition-overriding=true
spring.sql.init.schema-locations=classpath:init/schema.sql