spring.application.name=prescripto


spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

#spring.ai.vectorstore.pgvector.enabled=true
#spring.sql.init.mode=always
#spring.ai.ollama.base-url= http://ollama:11434
#spring.ai.ollama.chat.model=llama3
#spring.ai.vectorstore.pgvector.dimensions=768
## Embedding model
#spring.ai.ollama.embedding.model=nomic-embed-text


server.port=${SERVER_PORT:8090}

adminEmail=${ADMIN_EMAIL}
adminPassword=${ADMIN_PASSWORD}

spring.main.allow-bean-definition-overriding=true
spring.sql.init.schema-locations=classpath:init/schema.sql
#spring.sql.init.mode=always

# --- Redis Cloud (Upstash) ---
spring.redis.host=redis
spring.redis.port=6379
spring.redis.ssl.enabled=false
spring.redis.timeout=60000
spring.redis.url=${SPRING_REDIS_URL}

##### ----------- Stripe Configuration -----------
stripe.secret.Key=${STRIPE_SECRET_KEY}
stripe.CURRENCY = inr

card.number=4000003560000008 - successful card
